### ISSUE TITLE
Merge Javascript in ResourceServlet

### ISSUE THREAD

**Issue by arturnt** [asual/lesscss-servlet#10]
Since the Javascript is already being minified would be great to be able to specify a couple of files and for them to get merged and minified together.

**Comment by asual** [comment]
This is already supported for both CSS and JS. Check how the com.asual.lesscss.ResourcePackage is utilized in the following class:
https://github.com/asual/summer/blob/master/modules/lesspack/src/main/java/com/asual/summer/lesspack/HeadPackRenderer.java
