### ISSUE TITLE
Should not process .css files

### ISSUE THREAD

**Issue by leon** [asual/lesscss-servlet#11]
According to the lesscss.org spec

If you want to import a CSS file, and don’t want LESS to process it, just use the .css extension:

@import "lib.css";
The directive will just be left as is, and end up in the CSS output.

So that means the servlet isn't doing as it should.

**Comment by asual** [comment]
You're correct. I have exposed an option for CSS processing in the lesscss-engine project and it's enabled by default in lesscss-servlet. I will change the behavior to comply with the lesscss.org spec and make the current support optional.

**Comment by leon** [comment]
Awesome!

On Tue, Dec 6, 2011 at 1:18 PM, Rostislav Hristov <
reply@reply.github.com
