### ISSUE TITLE
option to enable closure vs. lesscss

### ISSUE THREAD

**Issue by leon** [asual/lesscss-servlet#12]
At the moment I cant turn off closure in the servlet if I only want to use the less parser.

Is there a way to add an option to turn on and of the closure compiler / compress option?

**Comment by asual** [comment]
Have you tried the "compress" init option mentioned in the README?

**Comment by leon** [comment]
Yes but this operates on both the less parser and the google closure
compiler.

It would be better if you could choose to enable them separately.

On Tue, Dec 6, 2011 at 1:33 PM, Rostislav Hristov <
reply@reply.github.com

**Comment by asual** [comment]
In other words it enables compression for both JS and CSS and you want more control over that.

**Comment by leon** [comment]
Yes. sometimes I do not want to process my javascript at all.

On Tue, Dec 6, 2011 at 1:39 PM, Rostislav Hristov <
reply@reply.github.com

**Comment by asual** [comment]
The project provides 2 servlets:
- ResourceServlet - appropriate for resources like css, js, images, fonts, etc.
- LessServlet - extends the ResourceServlet with lesscss processing

This basically means that you can configure both servlets separately and achieve the desired effect.
