### ISSUE TITLE
Imported files are not re-compiled in parent file on change

### ISSUE THREAD

**Issue by kirkov** [asual/lesscss-servlet#13]
If I have a `master.less` which imports a `base.less`. 
In my website I only include master.less.

Changes in `master.less` gets compiled on first new request, but if I only change `base.less`,  `master.less` will remain unchanged.
So I have to make a change (like a white space) in the `master.less`, for it to recompile.

**Comment by asual** [comment]
The servlet can be configured with a "cache" init-param. Have you tried setting it to false? The default behavior should be appropriate for production but if shouldn't allow changes like the ones you describe.

I just tried reproducing this in my setup and it seems to work as expected. The logic that handles such changes is located in com.asual.lesscss.LessResource.getLastModified(). It will be great if you can debug it to see if something special happens in your case.

Can you please try switching between these two syntax variants and see if something is improved:
@import url("base.css");
@import "base.css";

**Comment by kirkov** [comment]
Unfortunately, I don't longer have access to test this.
