### ISSUE TITLE
building the project to a jar file

### ISSUE THREAD

**Issue by igal-getrailo** [asual/lesscss-servlet#16]
is there a binary jar download?

I tried to build the project with Maven and I get the error below.  am I doing something wrong?

TIA

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 35.420s
[INFO] Finished at: Fri Jan 25 21:45:51 PST 2013
[INFO] Final Memory: 5M/244M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project lesscss-servlet: Could not resolve dependencies for project com.asual.lesscss:lesscss-servlet:jar:1.4.0-SNAPSHOT: Could not find artifact
com.asual.lesscss:lesscss-engine:jar:1.4.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by igal-getrailo** [comment]
I downloaded the binaries from
http://www.asual.com/maven/content/repositories/releases/com/asual/lesscss/

**Comment by asual** [comment]
The lesscss-engine and lesscss-servlet are related projects and for SNAPSHOTs you need to build both. The officially released artifacts are available in the Maven Central. I will soon release 1.4.2.
