### ISSUE TITLE
Clarify LESS servlet documentation

### ISSUE THREAD

**Issue by denizdogan** [asual/lesscss-servlet#25]
This seems like an awesome servlet, but I'm still having trouble understanding exactly how to configure it. It might be something else I've done wrong, but it would definitely help if the documentation clarifies a few things.

If I map the servlet to *.css, will it automagically compile and serve the corresponding .less file? Or do I need to map *.less for that?

Is the servlet required to be loaded before any other servlets, i.e. load-on-startup = 1?

And, although of less importance to me personally, maybe document all of the init parameters and their default values?

**Comment by tveimo** [comment]
You need to map it to *.less. The url you use in your jsp file will also be *.less, and that's what the browser will load.

**Comment by tveimo** [comment]
load-on-startup is not required
