### ISSUE TITLE
ResourceServlet : lastmodified check

### ISSUE THREAD

**Issue by sgunapu** [asual/lesscss-servlet#9]
Should this be ifModifiedSince/milliseconds >= lastModified/milliseconds? 

if (ifModifiedSince != 0 && ifModifiedSince/milliseconds == lastModified/milliseconds) {
                logger.debug("Return with SC_NOT_MODIFIED, since " + ifModifiedSince + " == " + lastModified);
                response.setStatus(HttpServletResponse.SC_NOT_MODIFIED);
                return;
            }

**Comment by asual** [comment]
In general your proposal is correct but how are you going to end up in a case that requires such a change?

**Comment by sgunapu** [comment]
I was implementing a resource concatenation servlet, which would send the most recent last modified date of all the resources to check individual resources for a 302.

**Comment by asual** [comment]
There is concatenation support already built in the project. It's handled primarily by the ResourcePackage class. Do you need help how to use it?
